trigger:
- master

variables: 
  LINUX_COMMON: "builtin_openssl=yes builtin_zlib=yes builtin_libpng=yes no_editor_splash=yes verbose=yes optimize=size"

jobs:

  - job: "mingw"
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install docker git -y
        docker build -f Dockerfile.mingw --tag mingw .
        git clone --depth 1 https://github.com/godotengine/godot
        cd godot
        docker run -v `pwd`:`pwd` -w `pwd` mingw scons p=windows target=release_debug -j5
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/godot/bin
 

  - job: "linux_tools_gcc_tools"
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install docker git -y
        docker build -f Dockerfile.linux-gcc --tag linux-gcc .
        git clone --depth 1 https://github.com/godotengine/godot --branch 3.2
        cd godot
        sed -i '/configure(/a \    env.Prepend(CCFLAGS=["-static"])' platform/x11/detect.py
        sed -i '/configure(/a \    env.Prepend(CFLAGS=["-static"])' platform/x11/detect.py
        sed -i '/configure(/a \    env.Prepend(CXXFLAGS=["-static"])' platform/x11/detect.py
        docker run -v `pwd`:`pwd` -w `pwd` linux-gcc scons p=x11 tools=yes target=release_debug $LINUX_COMMON -j5
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/godot/bin

  - job: "linux_gcc_export"
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install docker git -y
        docker build -f Dockerfile.linux-gcc --tag linux-gcc .
        git clone --depth 1 https://github.com/godotengine/godot --branch 3.2
        cd godot
        sed -i '/configure(/a \    env.Prepend(CCFLAGS=["-static"])' platform/x11/detect.py
        sed -i '/configure(/a \    env.Prepend(CFLAGS=["-static"])' platform/x11/detect.py
        sed -i '/configure(/a \    env.Prepend(CXXFLAGS=["-static"])' platform/x11/detect.py
        docker run -v `pwd`:`pwd` -w `pwd` linux-gcc scons p=x11 tools=no target=release_debug $LINUX_COMMON -j5
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/godot/bin
