
trigger:
- master

variables: 
  MY_INSTRUCTIONS: "-mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -msse4a -mcx16 -msahf -mno-movbe -mno-aes -mno-sha -mno-pclmul -mpopcnt -mabm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-wbnoinvd -mno-tbm -mno-avx -mno-avx2 -mno-sse4.2 -mno-sse4.1 -mlzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mprfchw -mno-adx -mfxsr -mno-xsave -mno-xsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-mwaitx"
  LINUX_INSTALL: "g++-9 git python-pip libasound2-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev"
  LINUX_OPTIONS: "builtin_openssl=yes builtin_zlib=yes builtin_libpng=yes use_static_cpp=yes no_editor_splash=yes verbose=yes"

jobs:
  ###### CREATE A RELEASE IN GITHUB
  - job: "create_github_release"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
    - task: GitHubRelease@0
      inputs:
        gitHubConnection: for-azure-scu
        repositoryName: santouits/test-lto-and-scu
        tagSource: manual
        tag: $(Build.BuildNumber)    
        addChangeLog: false
    displayName: 'create_github_release'

  ##### JOB 1 ######
  - job: "linux_tools_gnu_releasedebug_lto"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
    - script: |
        cat /etc/*-release
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get -qq update
        sudo apt-get -qq install $(LINUX_INSTALL) -y
        sudo ln -s /usr/bin/gcc-9 gcc
        sudo ln -s /usr/bin/g++-9 g++
        sudo ln -s /usr/bin/gcc-ar gcc-ar-9
        sudo ln -s /usr/bin/gcc-ranlib gcc-ranlib-9
        sudo ln -s /usr/bin/gcc-nm gcc-nm-9
        sudo pip install scons
        git clone --depth=1 https://github.com/godotengine/godot
        cd godot
        scons p=x11 -j5 tools=yes target=release_debug use_lto=yes debug_symbols=no CCFLAGS='-fno-fat-lto-objects -march=btver1 -mtune=btver1 $(MY_INSTRUCTIONS)' $(LINUX_OPTIONS)

    - task: CopyFiles@2
      inputs:
        contents: 'godot/bin/*' 
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: GitHubRelease@0
      inputs:
        action: edit
        gitHubConnection: for-azure-scu
        repositoryName: santouits/test-lto-and-scu
        tag: $(Build.BuildNumber)    
        assets: $(Build.ArtifactStagingDirectory)/**
        assetUploadMode: replace
        addChangeLog: false
    displayName: 'linux_tools_gnu_releasedebug_lto'

  ##### JOB 2 ######
  - job: "linux_tools_gnu_release_lto"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
    - script: |
        cat /etc/*-release
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get -qq update
        sudo apt-get -qq install $(LINUX_INSTALL) -y
        sudo ln -s /usr/bin/gcc-9 gcc
        sudo ln -s /usr/bin/g++-9 g++
        sudo ln -s /usr/bin/gcc-ar gcc-ar-9
        sudo ln -s /usr/bin/gcc-ranlib gcc-ranlib-9
        sudo ln -s /usr/bin/gcc-nm gcc-nm-9
        sudo pip install scons
        git clone --depth=1 https://github.com/godotengine/godot
        cd godot
        sed -i 's/O2/O3/g' platform/x11/detect.py
        sed -i 's/.opt.tools/.opt.tools.O3/g' SConstruct
        scons p=x11 -j5 tools=yes target=release_debug use_lto=yes debug_symbols=no CCFLAGS='-fno-fat-lto-objects -march=btver1 -mtune=btver1 $(MY_INSTRUCTIONS)' $(LINUX_OPTIONS)

    - task: CopyFiles@2
      inputs:
        contents: 'godot/bin/*' 
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: GitHubRelease@0
      inputs:
        action: edit
        gitHubConnection: for-azure-scu
        repositoryName: santouits/test-lto-and-scu
        tag: $(Build.BuildNumber)    
        assets: $(Build.ArtifactStagingDirectory)/**
        assetUploadMode: replace
        addChangeLog: false
    displayName: 'linux_tools_gnu_release_lto'
