
trigger:
- master

jobs:
  - job: "linux_tools_gnu_releasedebug_lto"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
    - script: |
        cat /etc/*-release
        sudo apt update
        sudo apt install git scons libasound2-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev -y
        git clone --depth=1 https://github.com/godotengine/godot
        cd godot
        scons p=x11 -j5 tools=yes target=release_debug use_lto=yes

    - task: CopyFiles@2
      inputs:
        contents: 'godot/bin/*' 
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: GitHubRelease@0
      inputs:
        gitHubConnection: for-azure-scu
        repositoryName: santouits/test-lto-and-scu
        tagSource: manual
        tag: $(Build.BuildNumber)    
        assets: $(Build.ArtifactStagingDirectory)/**
        addChangeLog: false
    displayName: 'test-re'
